### PR TITLE
⚡ Add autodock mock import config

### PR DESCRIPTION
**Pull request by Eiken**
* When generating sphinx api docs for a python module read the docsConfig.autodocMockImports attribute from the python package component.

### CODE REVIEW

**Comment by Eiken** [comment]
Why needed:
* Docs fails to generate when it cant find python modules

Reasons for putting it in `docsConfig.autodocMockImports`:
* Cant store on `docs`. The attribute gets stripped when passed to mkDocs
* Could potentially be put in the root repos toml file for nedryland controls but then it will be trickier to control per component
  * Maybe this config file should be changed name so it is more like pyproject.toml. Maybe nedry.toml? And also make it possible to use it per component instead of per project.

**Comment by Eiken** [comment]
Will update examples, changelog and etc when decided where the control should live

**Review by simonrainerson — APPROVED** [review]

**Comment by simonrainerson** [comment]
> Why needed:
> 
> * Docs fails to generate when it cant find python modules
> 
> Reasons for putting it in `docsConfig.autodocMockImports`:
> 
> * Cant store on `docs`. The attribute gets stripped when passed to mkDocs
> * Could potentially be put in the root repos toml file for nedryland controls but then it will be trickier to control per component
>   
>   * Maybe this config file should be changed name so it is more like pyproject.toml. Maybe nedry.toml? And also make it possible to use it per component instead of per project.

I think this is fine as a first step.

You have access to $src so you could parse a toml file in the configure phase to get the value to put in conf.py. Something like
```
${yq}/bin/tomlq -c '.docs.autodoc_mock_imports' < "$src/pyproject.toml" | sed 's/^/autodoc_mock_imports = /' >>doc-source/conf.py
```
and it would need to check that pyproject.toml exists, and handle the case where the setting isn't set etc. And add the dependency on yq at the top.

 The coolest thing imo would be some way of picking from docsConfig, falling back to something like pyproject.toml and then falling back to the nedryland project's toml.

**Comment by abbec** [comment]
> * Maybe this config file should be changed name so it is more like pyproject.toml. Maybe nedry.toml? And also make it possible to use it per component instead of per project.

But the purpose of that file is to configure project-wide things, and it can be called anything, it is just an argument to `mkProject`.

You can also just use pyproject.toml to store the configuration, in a `[tool.something]` section, which is similar to what Simon suggested.

**Comment by Eiken** [comment]
@abbec @simonrainerson 
> But the purpose of that file is to configure project-wide things, and it can be called anything, it is just an argument to `mkProject`.

Ahh, thought it auto found it in the root for some reason.

> You can also just use pyproject.toml to store the configuration, in a [tool.something] section, which is similar to what Simon suggested.

I thought about this but then I also thought that it should maybe only contain things that are actually "officially" supported by various python packages.

> I think this is fine as a first step.

So maybe this can go in as a first step / bug fix and we can update later if we find the need for a more elaborate solution?

**Comment by abbec** [comment]
> So maybe this can go in as a first step / bug fix and we can update later if we find the need for a more elaborate solution?

Absolutely.

**Comment by abbec** [comment]
> I thought about this but then I also thought that it should maybe only contain things that are actually "officially" supported by various python packages.

I think it is supposed to be extendable by any tool, official or not.

**Comment by Eiken** [comment]
Updated docs and changelog

**Review by abbec — APPROVED** [review]

**Pull request merged**
